---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# renv2binder

<!-- badges: start -->
<!-- badges: end -->

The goal of `renv2binder` is to convert lockfiles from `rv` and `renv` to a Binder friendly format.

[Binder](https://mybinder.org/) is a powerful tool for hands on reproducible research. You can add a button on your repository that will launch a Jupyter or RStudio instance that has your analysis code available, with all required packages. Under the hood, it uses a package called `repo2docker` that converts your repository to a Docker container with Jupyter/RStudio installed.

The main issue is that [Binder requires a `DESCRIPTION` or `install.R` file](https://repo2docker.readthedocs.io/en/latest/configuration/research/), which are not generated by `renv` or `rv`. This package will convert either type of lockfile to your choice of file into the root of your repository.

## Installation

You can install the development version of renv2binder like so:

``` r
pak::pak_install("laderast/renv2binder")
```

## Example

This is a basic example which shows you how to solve a common problem:

```r
library(renv2binder)
## basic example code
data(renv_lock)
renv_to_install_r(renv_lock,file_out="./install.R")
```

```

```